### ISSUE TITLE
Serial.print called in Graph.cpp but Arduino.h header is not installed

### ISSUE THREAD

**Issue by cHemingway** [jbowring/m5stack-teams-indicator#1]
E.g. https://github.com/jbowring/m5stack-teams-indicator/blob/94eca4fb68aeda8442585c61dc658469b6a8ba97/Graph.cpp#L57

Also `iostream` is included in this file, but is it needed?

**Comment by jbowring** [comment]
Good spot, fixed in 08d75b8febef2c301748c813d60f8985ff6c54fe
